---
version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw00rdROOT
      MYSQL_DATABASE: bibspace
      MYSQL_USER: bibspace_user
      MYSQL_PASSWORD: passw00rd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-ppassw00rdROOT"]
      timeout: 5s
      retries: 6

  bibspace:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ${PWD}/public/uploads:/BibSpace/public/uploads
      - ${PWD}/backups:/BibSpace/backups
      - ${PWD}/log:/BibSpace/log
      - ${PWD}/json_data:/BibSpace/json_data
      - ${PWD}/fixture:/BibSpace/fixture
    image: bibspace:latest
    restart: always
    ports:
      - "8083:8083"
    environment:
      BIBSPACE_RUN_MODE: production
      BIBSPACE_DB_HOST: db:3306
      BIBSPACE_DB_USER: bibspace_user
      BIBSPACE_DB_PASS: passw00rd
      BIBSPACE_DB_DATABASE: bibspace
      BIBSPACE_CONFIG: lib/BibSpace/files/config/default.conf
      BIBSPACE_USE_DUMP: 0
