#!/usr/bin/env perl

use Mojolicious::Lite;

app->hook(before_dispatch => sub {
  my $self = shift;
  
  my $use_prefix
    = $self->req->headers->header('X-ProxyPassReverse-UsePrefix');
  
  if (defined $use_prefix && lc $use_prefix eq 'on') {
    my $prefix = shift @{$self->req->url->path->parts};
    $self->req->url->base->path->parse("/$prefix");
  }
});

get '/' => 'index';

get '/foo' => 'foo';

app->config(hypnotoad => {listen => ['http://*:3001']});

app->start;

__DATA__

@@ index.html.ep

URL: <a href="<%= url_for '/foo' %>">Foo</a>

@@ foo.html.ep

Foo